services:
  ai-processor:
    build: .
    container_name: note-thing-ai-processor
    restart: unless-stopped
    volumes:
      - ./App:/App
    networks:
      - app_net
    depends_on:
      - database
      - queue
    environment:
      - GEMINI_API_KEY=${GEMINI_API_KEY}
      - MONGO_HOST=${MONGO_HOST}
      - MONGO_PORT=${MONGO_PORT}
      - MONGO_DB=${MONGO_DB}
      - MONGO_USER=${MONGO_USER}
      - MONGO_PASSWORD=${MONGO_PASSWORD}
      - REDIS_HOST=${REDIS_HOST}
      - REDIS_PORT=${REDIS_PORT}
      - REDIS_STREAM=${REDIS_STREAM}
      - REDIS_USER=${REDIS_USER}
      - REDIS_PASSWORD=${REDIS_PASSWORD}
networks:
  app_net:
    name: ${NETWORK_NAME}
    external: true
