services:
  delivery:
    build: .
    container_name: note-thing-delivery
    restart: unless-stopped
    volumes:
      - ./App:/App
      - ./crontab:/etc/cron.d/delivery-cron-source
    networks:
      - app_net
    depends_on:
      - database
    environment:
      - MONGO_HOST=${MONGO_HOST}
      - MONGO_PORT=${MONGO_PORT}
      - MONGO_DB=${MONGO_DB}
      - MONGO_USER=${MONGO_USER}
      - MONGO_PASSWORD=${MONGO_PASSWORD}
      - GEMINI_API_KEY=${GEMINI_API_KEY}

networks:
  app_net:
    name: ${NETWORK_NAME}
    external: true
