services:
  interaction:
    build:
      context: .
      dockerfile: Dockerfile
    container_name: note-thing-interaction
    volumes:
      - ./App:/app
    networks:
      - app_net
    environment:
      - REDIS_HOST=${REDIS_HOST}
      - REDIS_PORT=${REDIS_PORT}
      - REDIS_STREAM=${REDIS_STREAM}
      - REDIS_USER=${REDIS_USER}
      - REDIS_PASSWORD=${REDIS_PASSWORD}
      - MONGO_HOST=${MONGO_HOST}
      - MONGO_PORT=${MONGO_PORT}
      - MONGO_DB=${MONGO_DB}
      - MONGO_USER=${MONGO_USER}
      - MONGO_PASSWORD=${MONGO_PASSWORD}
networks:
  app_net:
    name: ${NETWORK_NAME}
    external: true
