services:
  interaction:
    build:
      context: .
      dockerfile: Dockerfile
    container_name: note-thing-interaction
    volumes:
      - ./App:/app
    networks:
      - app_net
    environment:
      - MONGO_HOST=${MONGO_HOST}
      - MONGO_PORT=${MONGO_PORT}
      - MONGO_DB=${MONGO_DB}
      - MONGO_USER=${MONGO_USER}
      - MONGO_PASSWORD=${MONGO_PASSWORD}
    depends_on:
      - database
      - nats
networks:
  app_net:
    name: ${NETWORK_NAME}
    external: true
